#!/usr/bin/python3

import requests
import os
import json
from datetime import datetime, timedelta
from dotenv import load_dotenv


load_dotenv()

class TemperatureNow():

    def __init__(self):
        self.API_KEY = os.getenv("API_KEY") 


        # URL
        self.base_url = "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/"
        self.url_endpoint = f"Stockholm?unitGroup=metric&key={self.API_KEY}&contentType=json"
        self.url = f"{self.base_url}{self.url_endpoint}"

        # Request data
        self.request = requests.get(self.url)
        self.data = self.request.content

    def latest_observed_date(self):
        """
        Returns the JSON object for the last observation date. 
        """
        date = datetime.today()

        while True:
            date_str = date.strftime("%Y-%m-%d")

            # Use the latest observation
            for day in json.loads(self.data)["days"]:
                if day["datetime"] == date_str:
                    return json.dumps(day, indent=2)
            
            # If the date is not found, go back one day
            date -= timedelta(days=1)

    def latest_observed_time(self):
        """
        Returns the JSON object for the last observation time that does not exceed the current time. 
        """
        json_last_date = json.loads(self.latest_observed_date())

        # Get the current time
        current_time = datetime.now().strftime("%H:%M:%S")
        # Get the last observation time object
        last_observation_time = None
        for time_obj in json_last_date.get("hours", []):
            if "datetime" in time_obj:
                observation_time = time_obj["datetime"]
                if observation_time <= current_time:
                    last_observation_time = time_obj
                else:
                    break

        return json.dumps(last_observation_time, indent=2)


    def output(self):
        latest_data_str = self.latest_observed_time()
        latest_data = json.loads(latest_data_str)

        # Accessing temperature and conditions directly
        temp = latest_data.get("temp", 25)
        conditions = latest_data.get("conditions", "Unknown")

        # Define color codes for different temperature ranges
        temp_ranges = {
            (-float('inf'), -10): "#8ecae6",
            (-10, 5): "#219ebc",
            (5, 10): "#023047",
            (10, 15): "#ffb703",
            (15, float('inf')): "#fb8500"
        }

        # Determine color based on temperature range
        temp_color = next(color for temp_range, color in temp_ranges.items() if temp_range[0] < temp <= temp_range[1])

        # Check UV index
        uv = f'UV-index: {latest_data.get("uvindex", "N/A")} | ' if temp >= 15 else ""

        # Format output with temperature and color
        icon = "󰏈"
        formatted_output = f'<span color="{temp_color}">{uv}{conditions} {icon} {temp:.2f} 󰔄 </span>'
        print(formatted_output)


temp_now = TemperatureNow()
latest_observed_time = temp_now.output()
